create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
create sequence ingredient_generator start with 1 increment by 1;
create sequence recipe_generator start with 1 increment by 1;
create table ingredients (id bigint not null, ingredient varchar(255), quantity varchar(255), version integer, recipe_id bigint not null, primary key (id));
create table recipes (id bigint not null, author varchar(255), instructions clob, name varchar(255), serves integer not null, vegetarian boolean not null, version integer, primary key (id));
alter table ingredients add constraint FK7p08vcn6wf7fd6qp79yy2jrwg foreign key (recipe_id) references recipes;
